name: Share Angular.io Develop CD

on:
  workflow_call:
    inputs:
      APP_NAME:
        required: true
        type: string
      ARTIFACT_NAME:
        required: true
        type: string
    secrets:
      STORAGE_ACCOUNT_CONNECTION_STRING:
        required: true
      AZURE_STATIC_WEB_APPS_API_TOKEN:
        required: true

jobs:
  deploy:
    name: Deploy built Angular.io app
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Download artifact from build job
        run: |
          export ARTIFACT_NAME=${{ inputs.ARTIFACT_NAME }}
          az storage blob download -c "build" -n ${ARTIFACT_NAME} -f ${GITHUB_WORKSPACE}/${ARTIFACT_NAME} --connection-string "${{ secrets.STORAGE_ACCOUNT_CONNECTION_STRING }}"
          unzip ${ARTIFACT_NAME}

      - name: Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "upload"
          app_location: "/dist/${{ inputs.APP_NAME }}/"
          output_location: ""
          skip_app_build: true