name: Retrieve latest built sha

on:
  workflow_call:
    outputs:
      firstword:
        description: "The first output string"
        value: ${{ jobs.example_job.outputs.output1 }}
      secondword:
        description: "The second output string"
        value: ${{ jobs.example_job.outputs.output2 }}

jobs:
  repository-dispatch:
    name: Repository dispatch
    runs-on: ubuntu-latest

    outputs:
      output1: ${{ steps.step1.outputs.firstword }}
      output2: ${{ steps.step2.outputs.secondword }}
    steps:
      - id: step1
        run: echo "::set-output name=firstword::hello"
      - id: step2
        run: echo "::set-output name=secondword::world"

    # outputs:
    #   output1: ${{ steps.retriver.outputs.sha }}

    # steps:
    #   - name: Checkout repository
    #     uses: actions/checkout@v3
    #     with:
    #       ref: 'main'
    #   - name: Retrieve latest artifact name
    #     id: retriver
    #     run: |
    #       ARTIFACT_NAME=$(cat latest-build-artifact)
    #       echo $ARTIFACT_NAME
    #       echo "::set-output name=sha::asdasdasdasdasdsa"


      
