name: Retrieve latest built sha

on:
  workflow_call:
    outputs:
      sha:
        description: "Github SHA of latest build"
        value: ${{ jobs.repository-dispatch.outputs.output1 }}

jobs:
  repository-dispatch:
    name: Repository dispatch
    runs-on: ubuntu-latest

    outputs:
      output1: ${{ steps.retriver.outputs.firstname }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: 'main'
      - id: retriver
        run: echo "::set-output name=firstname::"$(cat latest-build-artifact)


      
