name: Retrieve latest built sha

on:
  workflow_call:
    inputs:
      REPOSITORY:
        required: true
        type: string

jobs:
  repository-dispatch:
    name: Repository dispatch
    runs-on: ubuntu-latest

    outputs:
      sha: ${{ steps.retriver.outputs.sha }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: 'main'
      - id: retriver
        run: |
          ARTIFACT_NAME=$(cat latest-build-artifact)
          echo $ARTIFACT_NAME
          echo "::set-output name=sha::$ARTIFACT_NAME"


      
